### ISSUE TITLE
Z order and aspect ratio

### ISSUE THREAD

**Issue by IllidanS4** [groverburger/g3d#7]
The Z order of vertices in the example file is inverted, unlike in the screenshots in the repo:
![image](https://user-images.githubusercontent.com/1337208/92255258-57b14680-eed2-11ea-85e0-817785f8a4d0.png)

Additionally, the rendering aspect ratio is incorrectly set: squares appear as rectangles:
![image](https://user-images.githubusercontent.com/1337208/92255485-af4fb200-eed2-11ea-9aad-182adf4f44df.png)

Rotated 90 ° to the right:
![image](https://user-images.githubusercontent.com/1337208/92255512-baa2dd80-eed2-11ea-8687-e9d7a5303f8e.png)

Tested on the latest version of LÖVE.

**Comment by groverburger** [comment]
Aspect ratio problem is fixed, and you can change your own aspect ratio by modifying line 50 of camera.lua, or doing something like this: 
```
Camera.aspectRatio = some number
CameraShader:send("projectionMatrix", GetProjectionMatrix(Camera.fov, Camera.nearClip, Camera.farClip, Camera.aspectRatio))
```

Your Z ordering problem seems to be specific to your situation, I'm unsure of the solution and have not encountered the same problems with others. You can however set the depth mode to try to fix this issue, g3d by default initializes the depth mode as such: `love.graphics.setDepthMode("lequal", true)`

Hope that helps, I'm now closing this issue.

**Comment by IllidanS4** [comment]
Thanks for fixing the aspect ratio, but the second problem still persists. I have tried all values for `setDepthMode`, but it has no effect.

It also persists for the new example:
![image](https://user-images.githubusercontent.com/1337208/93571943-6fd69a80-f995-11ea-8ff4-451fe5d0551d.png)

I was a bit imprecise - the Z order isn't simply inverted, it almost seems simply ignored. Objects are drawn in front of each other regardless of their distance from the camera
